// Robots.txt Generator Script

function generateRobotsTxt() {
  const defaultRule = document.getElementById('robots-default-rule').value;
  const crawlDelay = document.getElementById('robots-delay').value;
  const sitemapUrl = document.getElementById('robots-sitemap').value.trim();
  const disallowsRaw = document.getElementById('robots-disallows').value;

  // Clean disallow paths
  const disallows = disallowsRaw
    .split('\n')
    .map(path => path.trim())
    .filter(path => path.length > 0);

  // Identify specific bot overrides
  const bots = [
    { id: 'bot-google', name: 'Googlebot' },
    { id: 'bot-google-img', name: 'Googlebot-Image' },
    { id: 'bot-bing', name: 'Bingbot' },
    { id: 'bot-yandex', name: 'Yandex' },
    { id: 'bot-baidu', name: 'Baiduspider' },
    { id: 'bot-duck', name: 'DuckDuckBot' }
  ];

  let output = `# robots.txt generated by SatX Tools (https://tools.satex.fun)\n# Created: ${new Date().toISOString().split('T')[0]}\n\n`;

  // Write blocks for specific blocked bots (if user unchecked them)
  let blockedBotsCount = 0;
  bots.forEach(bot => {
    const isChecked = document.getElementById(bot.id).checked;
    if (!isChecked) {
      output += `User-agent: ${bot.name}\nDisallow: /\n\n`;
      blockedBotsCount++;
    }
  });

  // Write default bot rules
  output += `User-agent: *\n`;

  if (defaultRule === 'disallow') {
    output += `Disallow: /\n`;
  } else {
    if (disallows.length === 0) {
      output += `Disallow:\n`;
    } else {
      disallows.forEach(path => {
        // Ensure path starts with a slash
        let formattedPath = path;
        if (!formattedPath.startsWith('/')) {
          formattedPath = '/' + formattedPath;
        }
        output += `Disallow: ${formattedPath}\n`;
      });
    }
    
    // Add Crawl Delay if set
    if (crawlDelay) {
      output += `Crawl-delay: ${crawlDelay}\n`;
    }
  }

  // Write Sitemap URL at the end
  if (sitemapUrl) {
    output += `\nSitemap: ${sitemapUrl}\n`;
  }

  document.getElementById('robots-output-code').textContent = output.trim();
}

function copyRobotsTxt(btn) {
  const codeElement = document.getElementById('robots-output-code');
  navigator.clipboard.writeText(codeElement.textContent).then(() => {
    const originalText = btn.innerHTML;
    btn.innerHTML = `<svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round" style="color: var(--green);"><polyline points="20 6 9 17 4 12"></polyline></svg> Copied!`;
    btn.classList.add('btn-success');
    setTimeout(() => {
      btn.innerHTML = originalText;
      btn.classList.remove('btn-success');
    }, 2000);
  }).catch(err => {
    console.error('Failed to copy text: ', err);
  });
}

function downloadRobotsTxt() {
  const text = document.getElementById('robots-output-code').textContent;
  const blob = new Blob([text], { type: 'text/plain' });
  const anchor = document.createElement('a');
  anchor.download = 'robots.txt';
  anchor.href = window.URL.createObjectURL(blob);
  anchor.style.display = 'none';
  document.body.appendChild(anchor);
  anchor.click();
  document.body.removeChild(anchor);
}

// Run initial generator
document.addEventListener('DOMContentLoaded', () => {
  generateRobotsTxt();
});

// Run immediately too
generateRobotsTxt();
